# Generated by Django 5.0 on 2023-12-29 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbi', '0006_alter_reporte_grupo'),
        ('pbi', '0006_customuser_cambio_primera_contrasena'),
    ]

    operations = [
    ]
